spring:
  profiles:
    active: @profiles.active@
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1023239574/microservice-config-repo
          username: 1023239574@qq.com
          password: ly52499698
          clone-on-start: true
#  开启安全验证
  security:
    user:
      name: user
      password: 123

eureka:
  client:
    # 开启健康检查
    healthcheck:
      enabled: true
    fetch-registry: true
  instance:
    prefer-ip-address: true




#logging:
#  level:
#    org.springframework.cloud: debug
#    org.springframework.boot: debug