spring:
  redis:
    # Redis服务器地址
    host: ${spring.redis.host}
    # Redis服务器连接端口
    port: ${spring.redis.port}
    # Redis服务器连接密码（默认为空）
    password: ${spring.redis.password}
  kafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: 192.168.244.129:9092