server:
  port: ${server.provider2_port}
spring:
  application:
    name: microservice-simple-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      max-active: 10
      min-idle: 10
      max-wait: 60000
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 10000
      min-evictable-idle-time-millis: 300000
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filters: stat,wall
  kafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: localhost:9092
    consumer:
      # 指定默认消费者group id
      group-id: test-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      # 指定消息key和消息体的编解码方式
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
eureka:
  instance:
    #访问路径可以显示ip地址
    prefer-ip-address: true
    #自定义服务名称信息
    instance-id: provider-2:${server.provider2_port}
  client:
    # 开启健康检查
    healthcheck:
      enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

ribbon:
  eureka:
    enabled: true

logging:
  logging:
    config: classpath:logback-spring.xml

# 暴露端点 *表示暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

# druid连接池监控页面登录用户名密码
druid:
  username: ${druid.username}
  password: ${druid.password}