server:
  port: ${server.zuul_port}

spring:
  application:
    name: microservice-gateway-Zuul

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  gateway-Zuul:${server.zuul_port}
  client:
    # 开启健康检查
    healthcheck:
      enabled: true

zuul:
 # strip-prefix: false
  routes:
    demo-route:
      service-id: microservice-simple-demo
      path: /consumer/**
    provider1-route:
      service-id: microservice-simple-provider
      path: /provider1/**
    provider2-route:
      service-id: microservice-simple-provider
      path: /provider2/**
  ribbon:
    eager-load:
      enabled: true
  retryable: true

# 暴露端点 *表示暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    com.netflix: debug

#hystrix超时时间配置,默认1s
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 5000
  ConnectTimeout: 5000
