server:
  port: ${server.provider_port}

spring:
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  kafka:
    # 指定kafka 代理地址，可以多个
    bootstrap-servers: 127.0.0.1:9092

eureka:
  instance:
    instance-id: provider-1:${server.provider_port}

# druid连接池监控页面登录用户名密码
druid:
  username: ${druid.username}
  password: ${druid.password}